version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kumunzee_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kumunzee
      POSTGRES_USER: kumunzee_user
      POSTGRES_PASSWORD: kumunzee_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
